kind: HealthCheckPolicy
apiVersion: networking.gke.io/v1
metadata:
  name: lb-healthcheck  
spec:
  default:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 2    
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_FIXED_PORT
        port: 80        
        host: onix-dev.gcpwkshpdev.com
        requestPath: /smoke            
  targetRef:
    group: ""
    kind: Service
    name: gkegw1-jsi5-aggregator-dev-translateapp-svc-80-3c2fn98ebyw5