deployment:
  name: genaitextapp-deploy
  serviceAccount: vertexai-sa
  labels:
    app: genaitextapp-deploy 
    version: v1
  selectorLabels:
    app: genaitextapp-pod
    version: v1
  replicas: 1
  strategyType: RollingUpdate
  maxSurge: 1
  maxUnavailable: 0
  nodeSelector:
    cloud.google.com/gke-nodepool: gkeappspool
  containers:
  - name: genaitext-app
    image: "/genai-textlib:v1.0"
    imagePullPolicy: Always
    memoryRequest: "500Mi"
    cpuRequest: "500m"
    memoryLimit: "1Gi"
    cpuLimit: "1"
    containerPorts: [6065]
    envVars:
    - name: WEBSOCK_STREAMER_HTTP_HOST      
      value: http://streamer-serverapp-svc.utilities-dev.svc
    - name: GENAI_LOCATION
      value: us-central1
    - name: GENAI_PUBLISHER
      value: google
    - name: GENAI_API_ENDPOINT
      value: us-central1-aiplatform.googleapis.com
    - name: GENAI_GEMINI_TEXT_MODEL
      value: gemini-1.5-pro
    - name: MODEL_PROJECT_ID
      value: 
    - name: MODEL_LOCATION
      value: us-central1
    - name: PROJECT_ID
      value: 
service:
  name: genaitextapp-svc
  selector:
    app: genaitextapp-pod
  type: ClusterIP
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 6065