apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:  
  name: translate-healthcheck
spec:
  default:
    checkIntervalSec: 15
    config:
      httpHealthCheck:
        port: 6061
        portSpecification: USE_FIXED_PORT
        requestPath: "/healthz"
      type: HTTP
    healthyThreshold: 1
    timeoutSec: 15
    unhealthyThreshold: 2
  targetRef:
    group: ''
    kind: Service
    name: translateapp-svc
