deployment:
  name: master-agriagent-deploy
  serviceAccount: aggregator-dev-sa
  labels:
    app: master-agriagent-deploy 
    version: v1
  selectorLabels:
    app: master-agriagent-pod
    version: v1
  replicas: 1
  strategyType: RollingUpdate
  maxSurge: 1
  maxUnavailable: 0
  nodeSelector:
    cloud.google.com/gke-nodepool: worker-pool
  containers:
  - name: master-agriagent-app
    image: "<repo-name>/master-agent:v1.0"
    imagePullPolicy: Always
    memoryRequest: "500Mi"
    cpuRequest: "500m"
    memoryLimit: "1Gi"
    cpuLimit: "1"
    containerPorts: [10003]
    envVars:    
    - name: AGENTIC_VERSION
      value: "1.0.0"
    - name: AGENTIC_DOMAIN_PREFIX
      value: "domain:"
    - name: AGENTIC_NLP_PROMPT
      value: "Convert the following sentence into a JSON object and return as a proper JSON.\nDo not add any new items into the response.\nConditions:\nDomain for any query on Agricultural Loan for Farmers will be \"AGRI\"\nDomain for search query on Weather Forecast will be \"WEATHER\"\nDomain for search query on Videos and Webinars will be \"VIDEO\"\nDomain for search query on the price of any Agriculture Products or Commodities in a Mandi or Market will be \"ENAM\"\nDomain for any Generic query on Agriculture asking for suggestions, guidance, help or queries on Farming Advisory etc. will be \"LLM\"\nDomain for any transactional query on Agriculture asking for Buying, Viewing of agricultural products will be \"AGRI\" with \"type\" as \"agri-commerce\"\nDomain for any transactional query on Retail Commerce asking for Buying, Viewing, Selling of non-agricultural products etc. will be \"AGRI\" with \"type\" as \"retail-commerce\"\nDomain for any transactional query on Agriculture asking for Selling of agricultural products or queries on Market Linkage will be \"AGRI\" with \"type\" as \"market-linkage\"\nDomain for any negative, irrelevant, abusive query which is out of any of the above contexts will be \"LLM\""
    - name: AGENTIC_MODEL_ENDPOINT_ID
      value: ""
    - name: STORAGELIB_HOST
      value: http://storageapp-svc.utilities-dev.svc
    - name: TRANSLATELIB_HOST
      value: http://translateapp-svc.vertexai-dev.svc
    - name: GENAI_IMAGELIB_HOST
      value: http://genaiimageapp-svc.vertexai-dev.svc
    - name: GENAI_VECTORSEARCHLIB_HOST
      value: http://vectorsearchapp-svc.vertexai-dev.svc
    - name: GENAI_TEXTLIB_HOST
      value: http://genaitextapp-svc.vertexai-dev.svc
    - name: GENAI_MULTILIB_HOST
      value: http://genaimultimodalapp-svc.vertexai-dev.svc
    - name: AGRI_AGENT_URL
      value: http://agriagent-svc.aggregator-dev.svc
    - name: VIDEO_AGENT_URL
      value: http://videoagent-svc.aggregator-dev.svc
    - name: WEATHER_AGENT_URL
      value: http://weatheragent-svc.aggregator-dev.svc
    - name: MANDI_AGENT_URL
      value: http://mandiagent-svc.aggregator-dev.svc
    - name: LLM_AGENT_URL
      value: http://llmagent-svc.aggregator-dev.svc
    - name: WEATHER_API_KEY
      value: x-api-weather-key
    - name: PARTNER_WEATHER_API_KEY
      value: x-partner-api-weather-key    
    - name: ENAM_MANDI_API_KEY
      value: x-api-mandi-key
    - name: PARTNER_MANDI_API_KEY
      value: x-partner-api-mandi-key
    - name: VIDEO_API_KEY
      value: x-api-video-key
    - name: PROJECT_ID
      value: <PROJECT_ID>
service:
  name: master-agriagent-svc
  selector:
    app: master-agriagent-pod
  type: ClusterIP
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 10003
hpa:
  name: master-agriagent-hpa
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: master-agriagent-deploy
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80