deployment:
  name: mandiagent-deploy
  serviceAccount: aggregator-dev-sa
  labels:
    app: mandiagent-deploy 
    version: v1
  selectorLabels:
    app: mandiagent-pod
    version: v1
  replicas: 1
  strategyType: RollingUpdate
  maxSurge: 1
  maxUnavailable: 0
  nodeSelector:
    cloud.google.com/gke-nodepool: worker-pool
  containers:
  - name: mandiagent-app
    image: "<repo-name>/mandi-agent:v1.0"
    imagePullPolicy: Always
    memoryRequest: "500Mi"
    cpuRequest: "500m"
    memoryLimit: "1Gi"
    cpuLimit: "1"
    containerPorts: [10002]
    envVars:
    - name: MANDI_ADAPTER_URL
      value: http://mandiadapter-svc.aggregator-dev.svc
    - name: ENAM_NETWORK_KEY
      value: ENAM
    - name: ENAM_MANDI_API_KEY
      value: x-api-mandi-key
    - name: PARTNER_MANDI_API_KEY
      value: x-partner-api-mandi-key
    - name: PROJECT_ID
      value: <PROJECT_ID>
service:
  name: mandiagent-svc
  selector:
    app: mandiagent-pod
  type: ClusterIP
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 10002  