deployment:
  name: videoagent-deploy
  serviceAccount: aggregator-dev-sa
  labels:
    app: videoagent-deploy 
    version: v1
  selectorLabels:
    app: videoagent-pod
    version: v1
  replicas: 1
  strategyType: RollingUpdate
  maxSurge: 1
  maxUnavailable: 0
  nodeSelector:
    cloud.google.com/gke-nodepool: worker-pool
  containers:
  - name: videoagent-app
    image: "<repo-name>/video-agent:v1.0"
    imagePullPolicy: Always
    memoryRequest: "500Mi"
    cpuRequest: "500m"
    memoryLimit: "1Gi"
    cpuLimit: "1"
    containerPorts: [10002]
    envVars:
    - name: VIDEO_ADAPTER_URL
      value: http://videoadapter-svc.aggregator-dev.svc
    - name: GENAI_TEXTLIB_HOST
      value: http://genaitextapp-svc.vertexai-dev.svc    
    - name: VIDEO_API_KEY
      value: x-api-video-key
    - name: YOUTUBE_NETWORK_KEY
      value: YOUTUBE
    - name: AGRI_ATTRIBUTES_PROMPT
      value: "Extract keywords related to Agriculture from the following sentence and return as a JSON response.Exclude all other types of keywords:\nExamples:\n\nQuery: Show me videos for rice farming\nResponse: {\"attributes\":[\"rice farming\"]}\n\nQuery: Show me videos for mango farming and C++ programming\nResponse: {\"attributes\":[\"mango farming\"]}\n\nQuery: Show me videos on Mango and Rice\nResponse: {\"attributes\":[\"mango\", \"rice\"]}\n\nQuery: Show me videos for Python programming\nResponse: {\"attributes\":[\"\"]}"
    - name: PROJECT_ID
      value: <project-id>
service:
  name: videoagent-svc
  selector:
    app: videoagent-pod
  type: ClusterIP
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 10002  