deployment:
  name: llmadapter-deploy
  serviceAccount: aggregator-dev-sa
  labels:
    app: llmadapter-deploy 
    version: v1
  selectorLabels:
    app: llmadapter-pod
    version: v1
  replicas: 1
  strategyType: RollingUpdate
  maxSurge: 1
  maxUnavailable: 0
  nodeSelector:
    cloud.google.com/gke-nodepool: worker-pool
  containers:
  - name: llmadapter-app
    image: "<repo-name>/llm-adapter:v1.0"
    imagePullPolicy: Always
    memoryRequest: "500Mi"
    cpuRequest: "500m"
    memoryLimit: "1Gi"
    cpuLimit: "1"
    containerPorts: [10001]
    envVars:    
    - name: EVENT_RECEIVER_HTTP_HOST
      value: http://event-receiverapp-svc.utilities-dev.svc
    - name: GENAI_TEXTLIB_HOST
      value: http://genaitextapp-svc.vertexai-dev.svc
    - name: LLM_CHAT_PROMPT
      value: "Generate a detailed response to the following chat query.\nTry to provide a complete solution to the query which should provide a defnite answer without asking too many questions back to the user.\nThe response should strictly within 300 words.\nThe response should be in the form of a nicely formatetd paragraph with proper line breaks and spacing.\nThe query needs to be from any one of the following domains:\n\"Agriculture\", \"Agri Advisory\" or \"Agri Market Linkage\", \"Retail\", \"Education\", \"Skilling\", \"Jobs\", \"Travel\", \"Hospitality\", \"Health\"\n. If the query is outisde any one of the above mentioned domains or if the query is negative, irrleveant or abusive, then generate a polite, generous response informing your inability to respond to this query.\nIf the query is about any person, celebrity, popular figure or any individual then generate a polite, short, crisp, generous response informing your inability to respond to this query; do not mention the name of that individual in the response.\nIf the query contains a greeting gesture like \"Hi\", \"Hello\" etc. then reciprocate back with a very polite and helpful response to make the user more comfortable with the system."
    - name: LLM_FOLLOW_UP_PROMPT
      value: "Generate a set of 3 alternate questions for the following.\nThe original query is asked by end user to a conversational bot; the follow up questions should follow the same context and should be asked as if user is asking to the bot.\nOne of the alternate question should be related to Video relevant to the original question.\nEach Question should be short and concise.\nReturn the response as a JSON in the following format:\n{\"follow_up\": {\"original_query\": \"I want to plan the marriage of my daughter.\", \"follow_ups\": [{\"follow_up\": \"I am looking for wedding planning advice and guidance for the upcoming marriage of my daughter.\"}, {\"follow_up\": \"What are the steps and resources needed to organize wedding?\"}, {\"follow_up\": \"Show me some videos giving ideas of marriage planning\"}]}}"
    - name: PROJECT_ID
      value: <project-id>
service:
  name: llmadapter-svc
  selector:
    app: llmadapter-pod
  type: ClusterIP
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 10001
hpa:
  name: llmadapter-hpa
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: llmadapter-deploy
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80